apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-domain-service
  name: account-domain-service
  namespace: multi-tenant-namespace
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8082
  selector:
    app: account-domain-service
    role: internal