apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-domain-service
  name: identity-domain-service
  namespace: multi-tenant-namespace
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: identity-domain-service
    role: internal